/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary":                  "#c0c1ff",
        "on-surface-variant":         "#c6c6ca",
        "on-secondary-container":     "#acaeff",
        "secondary-container":        "#2e2ebe",
        "secondary-fixed":            "#e1e0ff",
        "on-secondary":               "#0f00a9",
        "surface-container-lowest":   "#0b0f10",
        "surface-dim":                "#101415",
        "surface":                    "#101415",
        "surface-container-low":      "#181c1d",
        "surface-container":          "#1c2021",
        "surface-container-high":     "#272b2c",
        "surface-container-highest":  "#313536",
        "surface-variant":            "#313536",
        "surface-bright":             "#363a3b",
        "outline-variant":            "#45474a",
        "outline":                    "#909095",
        "on-surface":                 "#e0e3e4",
        "on-background":              "#e0e3e4",
        "primary":                    "#e2e2e6",
        "primary-fixed":              "#e2e2e6",
        "primary-container":          "#c6c6ca",
        "primary-fixed-dim":          "#c6c6ca",
      },
      fontFamily: {
        "display-xl":      ["Hanken Grotesk", "sans-serif"],
        "headline-lg":     ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md":     ["Hanken Grotesk", "sans-serif"],
        "body-lg":         ["Inter", "sans-serif"],
        "body-md":         ["Inter", "sans-serif"],
        "label-mono":      ["JetBrains Mono", "monospace"],
        "label-mono-sm":   ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg":     ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md":     ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-mono":  ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "500" }],
        "label-mono-sm": ["10px", { lineHeight: "1.2", fontWeight: "500" }],
      },
      spacing: {
        "margin-mobile":      "20px",
        "unit":               "4px",
        "gutter":             "24px",
        "section-padding-lg": "180px",
        "section-padding-md": "120px",
        "margin-desktop":     "64px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
}
